#!/bin/sh

FREEBSD_VBOXFS_DIR=~/freebsd-vboxfs
VIRTUALBOX_OSE_ADDITIONS_DIR=~/virtualbox-ose-additions

FREEBSD_VBOXVFS_PATH=src/VBox/Additions/freebsd/vboxvfs

VIRTUALBOX_OSE_ADDITIONS_WRKSRC=`cd ${VIRTUALBOX_OSE_ADDITIONS_DIR}; make -V WRKSRC`

rm -fr ${VIRTUALBOX_OSE_ADDITIONS_WRKSRC}/${FREEBSD_VBOXVFS_PATH}
mkdir ${VIRTUALBOX_OSE_ADDITIONS_WRKSRC}/${FREEBSD_VBOXVFS_PATH}

for f in `ls ${FREEBSD_VBOXFS_DIR}/vboxvfs/`
do
	ln -sv ${FREEBSD_VBOXFS_DIR}/vboxvfs/$f \
		${VIRTUALBOX_OSE_ADDITIONS_WRKSRC}/${FREEBSD_VBOXVFS_PATH}/$f
done
